### ISSUE TITLE
Allow translators to sort the word order of an address

### ISSUE THREAD

**Issue by ryonakano** [aggalex/Contacts#10]
At the moment the word order of addresses is English one even if the app UI is Japanese. In Japanese it should be `〒\<postal code\> \<state name\>\<city name\>\<street name\>`―like `〒123-4567 愛知県名古屋市中区123-4567` instead of `中区123-4567, 名古屋市, 愛知県, 123-4567, 日本`.

![Screenshot from 2019-07-21 00-58-34](https://user-images.githubusercontent.com/26003928/61581084-83e5f880-ab54-11e9-92d3-5605913412cb.png)

I would appreciate it if there would be a way for translators to change the word order of address.

**Comment by aggalex** [comment]
Great idea. I will probably have to implement a string that modifies the order accordingly like

**Comment by aggalex** [comment]
I realized that you also meant ommiting the commas. I sadly don't think I can do this right now. I'll try in the future though! For now, let's just implement the order.

**Comment by aggalex** [comment]
Done! Would you mind to test out my changes?

**Comment by ryonakano** [comment]
![Screenshot from 2019-07-21 09-18-10](https://user-images.githubusercontent.com/26003928/61585770-e19f3280-ab9e-11e9-9f87-4566d8b94b39.png)

Thank you for your work, it looks good to me!

However, there's just one thing which I found while I was changing the order of address with the po file.
The address part of the current `ja.po` looks like this:

```po
#: src/View/Contact.vala:68
msgid "$0, "
msgstr "〒$3 "

#: src/View/Contact.vala:69
msgid "$1, "
msgstr "$2"

#: src/View/Contact.vala:70
msgid "$2, "
msgstr "$1"

#: src/View/Contact.vala:71
msgid "$3, "
msgstr "$0"

#: src/View/Contact.vala:72
msgid "$4, "
msgstr ", $4"
```

And when I remove a comma from this part:

```diff
#: src/View/Contact.vala:72
msgid "$4, "
-msgstr ", $4"
+msgstr "$4"
```

then the app windows will never be shown.

I'm not sure whether there is a country which does not include any comma in addresses at all, but if so I think the app will not work well with that format.

**Comment by aggalex** [comment]
Oh man! I didn't test that. Let me do some work and I'll commit and push!

**Comment by aggalex** [comment]
The crash does not seen to happen at all in my system. Please try it again, and if you still have problems, open another issue I guess...

**Comment by aggalex** [comment]
Edit: the window hanged when I used Kanji (???)

**Comment by aggalex** [comment]
Please watch #11 from now on
