### ISSUE TITLE
When using kanji in the address, the window is prone to hangs

### ISSUE THREAD

**Issue by aggalex** [aggalex/Contacts#11]
`〒日本日本日本日本日本` worked ✔ 
`〒中区123-4567中区123-4567中区123-4567中区123-4567中区123-4567` hanged ⨯
`〒名古屋市名古屋市名古屋市名古屋市名古屋市` hanged ⨯
`〒123-4567愛知県名古屋市中区123-4567` worked ✔ 
`〒123-4567愛知県名古屋市中区123-4567日本` hanged ⨯

**Comment by aggalex** [comment]
Apparently my line-getting algorithm is what causes issues
![image](https://user-images.githubusercontent.com/11951328/61589434-5465d900-abb2-11e9-94ed-da126c44d643.png)

**Comment by aggalex** [comment]
Apparently things were caught inside an infinite loop in there due to the lack of spaces. the outer loop's condition was true, but the inner loop didn't change things. So I used a boolean flag called "changed" that signifies that a if no change happened, the outer loop should exit.
```vala
        private int get_lines () {
            int i = 1, j = 0;
            var text = new StringBuilder (label.get_text ());
            while (text.len > 40) {
                i++;
                j = 40;
                bool changed = false;
                do {
                    if (text.str.index_of_char (' ') < 0) break;
                    changed = true;
                    j = j - text.str.index_of_char (' ') - 1;
                    text.erase (0, text.str.index_of_char (' ')+1);
                } while (text.str.index_of_char (' ')+1 < j);
                if (!changed) break;
            }
            return i;
        }
```

**Comment by ryonakano** [comment]
Thank you for the quick fix!! :tada:
