### ISSUE TITLE
Improve Design when create a contact

### ISSUE THREAD

**Issue by aimproxy** [aggalex/Contacts#15]
Hi, there are various considerations to do about the design! When you click to create a contact its preferable if you go directory to the contact view instead of show an input box, personally its not to beauty. This issue should be labelled with `Needs Design`.

**Comment by aggalex** [comment]
A contact cannot exist with an empty name. Best I can do is add a placeholder text on the popup.

**Comment by aimproxy** [comment]
See how the gnome contact app work, you will understand better whats I'm trying to say.

**Comment by aggalex** [comment]
Oh, I have an idea: Create the contact page and immediately give the focus to the contact name entry
