### ISSUE TITLE
Editable Labels that have been constructed empty have empty entries

### ISSUE THREAD

**Issue by marbetschar** [aggalex/Contacts#29]
When I try to add a note (click on edit button), enter some text and then hit "Enter" the note disappears.

Sidenote: Would be awesome to be able to enter multi-line notes.

**Comment by marbetschar** [comment]
Same for Nickname. Maybe the issue is related to text fields within the "Miscellaneous" section.

**Comment by aggalex** [comment]
It seem to be an issue with EditableLabelNoType (The entry that goes inside the section)
