### ISSUE TITLE
Show what users should do when there's no contacts

### ISSUE THREAD

**Issue by ryonakano** [aggalex/Contacts#3]
![Screenshot from 2019-05-12 11-11-48](https://user-images.githubusercontent.com/26003928/57576919-c0d3a600-74a6-11e9-87fb-c47c453d27ce.png)

I think it would be helpful for users to show `Granite.Widgets.AlertView` in the right pane like this if there's no contacts e.g. on the first launch.

**Comment by aggalex** [comment]
Sure, I planned this for future releases

**Comment by aggalex** [comment]
Currently working on it. I'm planning to set the sidebar inside a Gtk.Revealer, and hide it when there aren't any contacts. But if this proves to be too big of a challenge, I think I'll  postpone it indefinitely and will work on the solution Mr. @ryonakano proposed. ありがとうございます、なかのさん！

**Comment by aggalex** [comment]
Done! You can try it. Alongside with this bug, I also fixed several instabilities. Right now, The app is almost stable enough for basic saving/loading of contacts.
