### ISSUE TITLE
"ESC" to abort editing

### ISSUE THREAD

**Issue by marbetschar** [aggalex/Contacts#30]
While in edit mode, hitting the escape key to abort editing would be cool.

**Comment by aggalex** [comment]
I'll try it

**Comment by marbetschar** [comment]
Sidenote: I highly appreciate all the effort you put into Contacts and really love where the app is heading. All issues I've opened are just ideas from my end, feel free to ignore/close where you don't see fit.

**Comment by aggalex** [comment]
Np, they are good Ideas.

**Comment by marbetschar** [comment]
Awesome! I LOVE it! 🎉🎉🎉
btw: "Anniversary" is "Jahrestag" in German :)
