### ISSUE TITLE
Birthday: Year

### ISSUE THREAD

**Issue by marbetschar** [aggalex/Contacts#32]
If the user adds a birthday, can we have the calendar show "current-year-minus-30-years" by default and/or add the ability to quickly move between the years?

Also it would be great to see the year and/or age of the person while in view-mode.

**Comment by aggalex** [comment]
Kinda hard, considering I'm using gtk's default calendar.

**Comment by marbetschar** [comment]
I see. Is it possible to simply set the default date to something like "current-year-minus-30-years"?

**Comment by aggalex** [comment]
I can try. But I can't promise anything about it...

**Comment by aggalex** [comment]
Done. You can test it

**Comment by marbetschar** [comment]
Awesome, thanks! One minor thing: On my end it does not show the year in view mode. Only the date ("Geburtstag: 26 Jun").

On the screenshot in the README the year is visible too. Maybe this is related to translation too? I use German.

**Comment by aggalex** [comment]
I switched to Granite formatting the dates to make sure it is automatically translated. I'll see if there's a way to add the year.

**Comment by aggalex** [comment]
done
