### ISSUE TITLE
"Website" as section

### ISSUE THREAD

**Issue by marbetschar** [aggalex/Contacts#33]
Is it possible to add a section called "websites"...? Similar to emails. This way we are able to add multiple websites per contact along with a label such as "work" or "private".

**Comment by aggalex** [comment]
The only currently available labels are Home, Work and Other. Affecting them might slip to the other sections too. So no, I don't think I can (currently) do this...

**Comment by marbetschar** [comment]
I'm perfectly fine with "Home", "Work" and "Other" labels for a website section. Given that "Websites" get their own section - which would add the ability to store multiple urls.

**Comment by aggalex** [comment]
Oh, you can already store multiple urls. The only thing you can't store permanently is Birthdays

**Comment by aggalex** [comment]
I can make a separate section though.

**Comment by aggalex** [comment]
I will do it tommorow

**Comment by aggalex** [comment]
Done.
ATTENTION! Please delete any contacts with websites in them. Or else you will be met with a segfault.
This issue will be fixed later.
