### ISSUE TITLE
"Smartphones" to "Phones"...?

### ISSUE THREAD

**Issue by marbetschar** [aggalex/Contacts#34]
Minor thing. Was just a bit irritated when I saw it the first time: The section header for "Smartphones" may just be titled with "Phone numbers" or "Phones". In case a distinction is needed, a simple "Mobile" label might do the job.

**Comment by aggalex** [comment]
Are you using some kind of translation? In English it's "Phones"

**Comment by marbetschar** [comment]
Good catch! Seems like the DE translation is wrong then. "Telefon" would be the correct translation then (whereas "Telefone" is the plural form - don't know whats the preferred one).

**Comment by aggalex** [comment]
I saw it too! I'll fix it now

**Comment by aggalex** [comment]
Done
