### ISSUE TITLE
Recommend to set up Travis CI

### ISSUE THREAD

**Issue by ryonakano** [aggalex/Contacts#48]
It's not necessary so if you don't wish that's OK, but it's recommended to set up Travis CI because you can notice any errors like #44 with detailed logs (like [this](https://travis-ci.org/ryonakano/Contacts/builds/571585672#L617-L620)) every time you push to the remote repository without making a new release.

All you need to do is:

* Add `travis.yml` (like [this](https://github.com/ryonakano/reco/blob/master/.travis.yml))
* Log in to https://travis-ci.org/
* In [the repositories page](https://travis-ci.org/account/repositories), enable Travis CI in the Contacts repository:

![Screenshot from 2019-08-14 20-13-52](https://user-images.githubusercontent.com/26003928/63017059-38630800-bed0-11e9-84d0-b82a0d1b567e.png)

And that's all! You can check whether CI checks pass in the commits page in GitHub every time you push new commits:

![Screenshot from 2019-08-14 20-16-55](https://user-images.githubusercontent.com/26003928/63017139-7d873a00-bed0-11e9-8e0e-84b7056d9a68.png)

Clicking "Details" allows you to view a whole log.

See also: https://github.com/elementary/houston/wiki/Continuous-Integration

**Comment by aggalex** [comment]
This. is. gold!
Thank you, you saved me lots of precious time with this.
