### ISSUE TITLE
Don't mention elementary OS in your description

### ISSUE THREAD

**Issue by danrabbit** [aggalex/Contacts#50]
every app in AppCenter is made for elementary OS, so this is not a unique selling point for your app

**Comment by aggalex** [comment]
OK, I will do this. Is it acceptable however to say this?

> Ability to import contacts from system (Evolution Data Server and Folks), which means ability to import contacts from online services (Google contacts integration planned by **elementary**).

It's still a mention to elementary OS, but I think that it is acceptable in this context.

**Comment by aggalex** [comment]
Gotcha. I'm gonna use "Google contacts not yet supported".

**Comment by yerbestpal** [comment]
This should now be closed, right?
