### ISSUE TITLE
Shoutout to @ryonakano for Japanese translations!

### ISSUE THREAD

**Issue by aggalex** [aggalex/Contacts#7]
Hey mr. @ryonakano, I'd be glad if you could translate the app to Japanese! 😜️😁️

**Comment by ryonakano** [comment]
Wow, I'd be glad to!! 😍💪

**Comment by aggalex** [comment]
@ryonakano, I've added some tooltips. Please make sure to check them out whenever you got some time to spare!
ご迷惑をおかけして、すみません...

**Comment by ryonakano** [comment]
That's all right, 大丈夫ですよ :smile:
I'll check and make a PR soon :+1:
