### ISSUE TITLE
Use Granite.DateTime.get_default_date_format for localized date format

### ISSUE THREAD

**Issue by ryonakano** [aggalex/Contacts#9]
At the moment the format of the date is English one even if the app UI is Japanese. In Japanese it should be "2019年7月21日" instead of "21 of July, 2019". ("年", "月", and "日" are kinds of suffix to represent year, month, and day. Also, "7月" means July.)

![Screenshot from 2019-07-21 00-50-05](https://user-images.githubusercontent.com/26003928/61580865-97439480-ab51-11e9-8aa9-723e266e91d7.png)

I thing using [`Granite.DateTime.get_default_date_format`](https://valadoc.org/granite/Granite.DateTime.get_default_date_format.html) allows us to show the localized date format with ease.

**Comment by aggalex** [comment]
Thanks for the heads up!!! Will immediately work on it.
